#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'postgresql'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'sqlite'

cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git',
  :ref => 'v0.9.0'

cookbook 'ufw',
  :git => 'git://github.com/opscode-cookbooks/ufw.git'